"""v2_saas_schema

Revision ID: 7383bf8ccdad
Revises: dda115785cd7
Create Date: 2026-04-06 07:21:08.405121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7383bf8ccdad'
down_revision: Union[str, Sequence[str], None] = 'dda115785cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_plots', sa.Integer(), nullable=False),
    sa.Column('processed_plots', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_project_id'), 'job_runs', ['project_id'], unique=False)
    op.create_table('plots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('plot_ref', sa.String(length=100), nullable=True),
    sa.Column('geometry_type', sa.String(length=20), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=False),
    sa.Column('bbox_minx', sa.Float(), nullable=True),
    sa.Column('bbox_miny', sa.Float(), nullable=True),
    sa.Column('bbox_maxx', sa.Float(), nullable=True),
    sa.Column('bbox_maxy', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plots_plot_ref'), 'plots', ['plot_ref'], unique=False)
    op.create_index(op.f('ix_plots_project_id'), 'plots', ['project_id'], unique=False)
    op.create_table('evidence_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_run_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('summary_snapshot', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_exports_job_run_id'), 'evidence_exports', ['job_run_id'], unique=False)
    op.create_table('plot_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_run_id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('ndvi_before', sa.Float(), nullable=True),
    sa.Column('ndvi_after', sa.Float(), nullable=True),
    sa.Column('delta_ndvi', sa.Float(), nullable=True),
    sa.Column('nbr_before', sa.Float(), nullable=True),
    sa.Column('nbr_after', sa.Float(), nullable=True),
    sa.Column('delta_nbr', sa.Float(), nullable=True),
    sa.Column('changed_area_ha', sa.Float(), nullable=True),
    sa.Column('cloud_fraction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('flag_reason', sa.String(length=300), nullable=True),
    sa.Column('before_scene_date', sa.String(length=30), nullable=True),
    sa.Column('after_scene_date', sa.String(length=30), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('reviewer_decision', sa.String(length=20), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plot_assessments_job_run_id'), 'plot_assessments', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_plot_assessments_plot_id'), 'plot_assessments', ['plot_id'], unique=False)
    op.drop_index(op.f('ix_parcels_parcel_ref'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_project_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_analysis_jobs_project_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_reports_job_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_parcel_results_job_id'), table_name='parcel_results')
    op.drop_index(op.f('ix_parcel_results_parcel_id'), table_name='parcel_results')
    op.drop_table('parcel_results')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.create_table('parcel_results',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parcel_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ndvi_before', sa.FLOAT(), nullable=True),
    sa.Column('ndvi_after', sa.FLOAT(), nullable=True),
    sa.Column('delta_ndvi', sa.FLOAT(), nullable=True),
    sa.Column('nbr_before', sa.FLOAT(), nullable=True),
    sa.Column('nbr_after', sa.FLOAT(), nullable=True),
    sa.Column('delta_nbr', sa.FLOAT(), nullable=True),
    sa.Column('changed_area_ha', sa.FLOAT(), nullable=True),
    sa.Column('cloud_fraction', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('flag_reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('before_scene_date', sa.VARCHAR(length=30), nullable=True),
    sa.Column('after_scene_date', sa.VARCHAR(length=30), nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=100), nullable=False),
    sa.Column('analyzed_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_results_parcel_id'), 'parcel_results', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_parcel_results_job_id'), 'parcel_results', ['job_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('triggered_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('total_parcels', sa.INTEGER(), nullable=False),
    sa.Column('processed_parcels', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_project_id'), 'analysis_jobs', ['project_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('parcel_ref', sa.VARCHAR(length=100), nullable=True),
    sa.Column('geometry_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('geojson', sa.TEXT(), nullable=False),
    sa.Column('bbox_minx', sa.FLOAT(), nullable=True),
    sa.Column('bbox_miny', sa.FLOAT(), nullable=True),
    sa.Column('bbox_maxx', sa.FLOAT(), nullable=True),
    sa.Column('bbox_maxy', sa.FLOAT(), nullable=True),
    sa.Column('area_ha', sa.FLOAT(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=10), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_project_id'), 'parcels', ['project_id'], unique=False)
    op.create_index(op.f('ix_parcels_parcel_ref'), 'parcels', ['parcel_ref'], unique=False)
    op.drop_index(op.f('ix_plot_assessments_plot_id'), table_name='plot_assessments')
    op.drop_index(op.f('ix_plot_assessments_job_run_id'), table_name='plot_assessments')
    op.drop_table('plot_assessments')
    op.drop_index(op.f('ix_evidence_exports_job_run_id'), table_name='evidence_exports')
    op.drop_table('evidence_exports')
    op.drop_index(op.f('ix_plots_project_id'), table_name='plots')
    op.drop_index(op.f('ix_plots_plot_ref'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_job_runs_project_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
