"""initial_schema

Revision ID: dda115785cd7
Revises: 
Create Date: 2026-04-06 06:25:28.709318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda115785cd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('origin_country', sa.String(length=10), nullable=True),
    sa.Column('cutoff_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_parcels', sa.Integer(), nullable=False),
    sa.Column('processed_parcels', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_project_id'), 'analysis_jobs', ['project_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('parcel_ref', sa.String(length=100), nullable=True),
    sa.Column('geometry_type', sa.String(length=20), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=False),
    sa.Column('bbox_minx', sa.Float(), nullable=True),
    sa.Column('bbox_miny', sa.Float(), nullable=True),
    sa.Column('bbox_maxx', sa.Float(), nullable=True),
    sa.Column('bbox_maxy', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_parcel_ref'), 'parcels', ['parcel_ref'], unique=False)
    op.create_index(op.f('ix_parcels_project_id'), 'parcels', ['project_id'], unique=False)
    op.create_table('parcel_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('ndvi_before', sa.Float(), nullable=True),
    sa.Column('ndvi_after', sa.Float(), nullable=True),
    sa.Column('delta_ndvi', sa.Float(), nullable=True),
    sa.Column('nbr_before', sa.Float(), nullable=True),
    sa.Column('nbr_after', sa.Float(), nullable=True),
    sa.Column('delta_nbr', sa.Float(), nullable=True),
    sa.Column('changed_area_ha', sa.Float(), nullable=True),
    sa.Column('cloud_fraction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('flag_reason', sa.String(length=200), nullable=True),
    sa.Column('before_scene_date', sa.String(length=30), nullable=True),
    sa.Column('after_scene_date', sa.String(length=30), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_results_job_id'), 'parcel_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_parcel_results_parcel_id'), 'parcel_results', ['parcel_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_job_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_parcel_results_parcel_id'), table_name='parcel_results')
    op.drop_index(op.f('ix_parcel_results_job_id'), table_name='parcel_results')
    op.drop_table('parcel_results')
    op.drop_index(op.f('ix_parcels_project_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_parcel_ref'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_analysis_jobs_project_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
