"""Evidence report generators for EUDR due diligence packages.

Generates JSON, CSV and PDF reports from analysis job results.

DISCLAIMER: Reports generated by this tool are for due diligence
pre-screening purposes only and do not constitute legal compliance
determinations under EUDR or any other regulatory framework.
"""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DISCLAIMER_EN = (
    "This report is generated by TraceCheck, an AI-assisted pre-screening tool for supply chain "
    "due diligence. The risk classifications provided herein are based on satellite-derived spectral "
    "indices (Sentinel-2, Copernicus) and do NOT constitute a legal determination of compliance with "
    "the EU Deforestation Regulation (EUDR/EU 2023/1115) or any other regulatory framework. "
    "All final compliance decisions remain the sole responsibility of the reporting organisation. "
    "Results may be affected by cloud cover, seasonal vegetation changes, and satellite data "
    "availability. Parcels classified as HIGH or REVIEW risk should be subject to independent "
    "expert review and, where appropriate, field verification."
)

DISCLAIMER_KO = (
    "본 보고서는 공급망 사전실사를 위한 AI 보조 사전점검 도구 TraceCheck에 의해 생성되었습니다. "
    "본 리스크 분류는 위성 기반 분광 지수(Sentinel-2, Copernicus)에 근거하며, "
    "EU 산림전용방지규정(EUDR/EU 2023/1115) 또는 기타 규제 프레임워크에 따른 "
    "법적 준수 여부의 최종 판정을 구성하지 않습니다. "
    "모든 최종 준수 결정에 대한 법적 책임은 보고 기관에 있습니다. "
    "HIGH 또는 REVIEW 등급 필지에 대해서는 전문가 검토 및 현장 실사를 병행하시기 바랍니다."
)


# ─────────────────────────────────────────────────────────────────────────────
# JSON Report
# ─────────────────────────────────────────────────────────────────────────────

def generate_json_report(
    job: Any,
    project: Any,
    user: Any,
    results: list[Any],
    summary: dict[str, int],
    output_path: Path,
) -> None:
    """Generate a structured JSON evidence package."""
    total = summary["total"]

    def pct(n: int) -> float:
        return round(n / total * 100, 1) if total > 0 else 0.0

    plot_list = []
    for r in results:
        # v2: r.plot (was r.parcel)
        plot = (
            r.plot if hasattr(r, "plot") and r.plot
            else r.parcel if hasattr(r, "parcel") and r.parcel
            else None
        )
        geojson = None
        if plot:
            try:
                geojson = json.loads(plot.geojson).get("geometry")
            except Exception:
                pass

        # Support both v1 (parcel_id/parcel_ref) and v2 (plot_id/plot_ref) field names
        plot_id = getattr(r, "plot_id", None) or getattr(r, "parcel_id", None)
        plot_ref = getattr(plot, "plot_ref", None) or getattr(plot, "parcel_ref", None)
        ts = getattr(r, "assessed_at", None) or getattr(r, "analyzed_at", None)

        plot_list.append({
            "plot_id": plot_id,
            "plot_ref": plot_ref,
            "supplier_name": getattr(plot, "supplier_name", None) if plot else None,
            "country": getattr(plot, "country", None) if plot else None,
            "geometry": geojson,
            "risk_level": r.risk_level,
            "delta_ndvi": r.delta_ndvi,
            "changed_area_ha": r.changed_area_ha,
            "cloud_fraction": r.cloud_fraction,
            "confidence": r.confidence,
            "flag_reason": r.flag_reason,
            "before_scene_date": r.before_scene_date,
            "after_scene_date": r.after_scene_date,
            "data_source": r.data_source,
            "assessed_at": ts.isoformat() if ts else None,
        })

    report = {
        "report_meta": {
            "tool": "TraceCheck",
            "tool_version": "0.2.0",
            "report_type": "EUDR_DUE_DILIGENCE_PRESCREENING",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": getattr(user, "email", "unknown"),
            "organisation": getattr(user, "org_name", None),
        },
        "project": {
            "id": project.id,
            "name": project.name,
            "commodity": project.commodity,
            "origin_country": project.origin_country,
            "cutoff_date": project.cutoff_date,
        },
        "analysis": {
            "job_run_id": job.id,
            "status": job.status,
            "started_at": job.started_at.isoformat() if job.started_at else None,
            "completed_at": job.completed_at.isoformat() if job.completed_at else None,
            "data_source": "Copernicus Sentinel-2 L2A",
            "eudr_cutoff_date": project.cutoff_date,
        },
        "summary": {
            "total_plots": total,
            "low": summary["low"],
            "review": summary["review"],
            "high": summary["high"],
            "low_pct": pct(summary["low"]),
            "review_pct": pct(summary["review"]),
            "high_pct": pct(summary["high"]),
        },
        "plots": plot_list,
        "disclaimer": {
            "en": DISCLAIMER_EN,
            "ko": DISCLAIMER_KO,
        },
        "risk_methodology": {
            "description": "Rule-based spectral index change detection using Sentinel-2 imagery",
            "indices_used": ["NDVI (Normalised Difference Vegetation Index)", "NBR (Normalised Burn Ratio)"],
            "low": "No significant vegetation change detected after EUDR cutoff date.",
            "review": (
                "Borderline change values OR high cloud coverage. "
                "Human expert review recommended before final due diligence submission."
            ),
            "high": (
                "Clear vegetation loss detected after EUDR cutoff date. "
                "Independent field verification strongly recommended."
            ),
        },
    }

    output_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# CSV Report
# ─────────────────────────────────────────────────────────────────────────────

def generate_csv_report(results: list[Any], output_path: Path) -> None:
    """Generate a flat CSV of all plot assessment results."""
    fieldnames = [
        "plot_ref", "supplier_name", "country",
        "risk_level", "delta_ndvi", "changed_area_ha",
        "cloud_fraction", "confidence", "flag_reason",
        "before_scene_date", "after_scene_date", "data_source", "assessed_at",
    ]

    with output_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in results:
            # v2: r.plot (was r.parcel)
            plot = (
                r.plot if hasattr(r, "plot") and r.plot
                else r.parcel if hasattr(r, "parcel") and r.parcel
                else None
            )
            plot_ref = getattr(plot, "plot_ref", None) or getattr(plot, "parcel_ref", None)
            ts = getattr(r, "assessed_at", None) or getattr(r, "analyzed_at", None)
            writer.writerow({
                "plot_ref": plot_ref or "",
                "supplier_name": getattr(plot, "supplier_name", "") if plot else "",
                "country": getattr(plot, "country", "") if plot else "",
                "risk_level": r.risk_level,
                "delta_ndvi": r.delta_ndvi,
                "changed_area_ha": r.changed_area_ha,
                "cloud_fraction": r.cloud_fraction,
                "confidence": r.confidence,
                "flag_reason": r.flag_reason or "",
                "before_scene_date": r.before_scene_date or "",
                "after_scene_date": r.after_scene_date or "",
                "data_source": r.data_source,
                "assessed_at": ts.isoformat() if ts else "",
            })


# ─────────────────────────────────────────────────────────────────────────────
# PDF Report
# ─────────────────────────────────────────────────────────────────────────────

def generate_pdf_report(
    job: Any,
    project: Any,
    user: Any,
    results: list[Any],
    summary: dict[str, int],
    output_path: Path,
) -> None:
    """Generate a PDF evidence report using reportlab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, HRFlowable
        )
        _generate_pdf_with_reportlab(job, project, user, results, summary, output_path)
    except ImportError:
        # Fallback: generate JSON with .pdf extension note
        json_path = output_path.with_suffix(".json")
        generate_json_report(job, project, user, results, summary, json_path)
        output_path.write_text(
            f"PDF generation requires reportlab. JSON report saved at {json_path.name}",
            encoding="utf-8",
        )


def _generate_pdf_with_reportlab(
    job: Any, project: Any, user: Any, results: list[Any],
    summary: dict[str, int], output_path: Path
) -> None:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, HRFlowable
    )

    doc = SimpleDocTemplate(str(output_path), pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # ── Title ─────────────────────────────────────────────────────────────────
    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=18, spaceAfter=6)
    story.append(Paragraph("TraceCheck — EUDR Pre-Screening Report", title_style))
    story.append(Paragraph(
        f"Project: <b>{project.name}</b> | Commodity: {project.commodity.upper()}",
        styles["Normal"]
    ))
    story.append(Paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | "
        f"Organisation: {getattr(user, 'org_name', 'N/A')}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%"))
    story.append(Spacer(1, 0.3*cm))

    # ── Summary ───────────────────────────────────────────────────────────────
    total = summary["total"]
    story.append(Paragraph("Risk Summary", styles["Heading2"]))

    def pct(n: int) -> str:
        return f"{round(n / total * 100, 1)}%" if total > 0 else "0%"

    summary_data = [
        ["Risk Level", "Count", "Percentage", "Action Required"],
        ["🟢 LOW", str(summary["low"]), pct(summary["low"]), "No action required"],
        ["🟡 REVIEW", str(summary["review"]), pct(summary["review"]), "Expert review recommended"],
        ["🔴 HIGH", str(summary["high"]), pct(summary["high"]), "Field verification required"],
        ["TOTAL", str(total), "100%", ""],
    ]
    tbl = Table(summary_data, colWidths=[4*cm, 2*cm, 3*cm, 7*cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a365d")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.HexColor("#f0fff4"), colors.HexColor("#fff9f0"), colors.HexColor("#fff5f5")]),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#e2e8f0")),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e0")),
        ("ALIGN", (1, 0), (2, -1), "CENTER"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.5*cm))

    # ── Parcel details (show HIGH and REVIEW) ─────────────────────────────────
    flagged = [r for r in results if r.risk_level in ("high", "review")]
    if flagged:
        story.append(Paragraph("Flagged Plots Requiring Review", styles["Heading2"]))
        parcel_data = [["Plot Ref", "Supplier", "Country", "Risk", "dNDVI", "Area (ha)", "Reason"]]
        for r in flagged[:100]:  # max 100 rows in PDF
            plot = (
                r.plot if hasattr(r, "plot") and r.plot
                else r.parcel if hasattr(r, "parcel") and r.parcel
                else None
            )
            plot_ref = getattr(plot, "plot_ref", None) or getattr(plot, "parcel_ref", None)
            plot_id_short = getattr(r, "plot_id", getattr(r, "parcel_id", "?"))[:8]
            parcel_data.append([
                plot_ref or plot_id_short,
                (getattr(plot, "supplier_name", "") or "")[:20],
                getattr(plot, "country", "") or "",
                r.risk_level.upper(),
                f"{r.delta_ndvi:.3f}" if r.delta_ndvi is not None else "N/A",
                f"{r.changed_area_ha:.2f}" if r.changed_area_ha is not None else "N/A",
                (r.flag_reason or "")[:30],
            ])
        pt = Table(parcel_data, repeatRows=1)
        pt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2d3748")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f7fafc")]),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(pt)
        story.append(Spacer(1, 0.5*cm))

    # ── Disclaimer ────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%"))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph("Disclaimer", styles["Heading3"]))
    disclaimer_style = ParagraphStyle("disclaimer", parent=styles["Normal"],
                                       fontSize=7, textColor=colors.HexColor("#718096"))
    story.append(Paragraph(DISCLAIMER_EN, disclaimer_style))

    doc.build(story)
